#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new \Symfony\Component\Console\Application('Petruk', '1.0.x');
$app->add(new \Ratno\Petruk\Console\RequireCommand);
$app->run();
